PROJ = top_icebreaker

PIN_DEF = icebreaker-examples/icebreaker/icebreaker.pcf
DEVICE = up5k
PACKAGE = sg48

ADD_SRC = tomkeddie_top_tto_a.v uart_tx.v

prog: iceprog

include icebreaker-examples/main.mk
